# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\MyProduct\Python\WB\changeBrand\ui\changeBrand.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(259, 256)
        self.timeStars = QtWidgets.QTabWidget(Form)
        self.timeStars.setGeometry(QtCore.QRect(0, 0, 261, 81))
        self.timeStars.setObjectName("timeStars")
        self.tabTime = QtWidgets.QWidget()
        self.tabTime.setObjectName("tabTime")
        self.TimeMultiBrand = QtWidgets.QTimeEdit(self.tabTime)
        self.TimeMultiBrand.setGeometry(QtCore.QRect(0, 0, 61, 22))
        self.TimeMultiBrand.setObjectName("TimeMultiBrand")
        self.TimeMobiBrand = QtWidgets.QTimeEdit(self.tabTime)
        self.TimeMobiBrand.setGeometry(QtCore.QRect(0, 30, 61, 22))
        self.TimeMobiBrand.setObjectName("TimeMobiBrand")
        self.label = QtWidgets.QLabel(self.tabTime)
        self.label.setGeometry(QtCore.QRect(70, 0, 151, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabTime)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 171, 16))
        self.label_2.setObjectName("label_2")
        self.timeStars.addTab(self.tabTime, "")
        self.tabPeriod = QtWidgets.QWidget()
        self.tabPeriod.setObjectName("tabPeriod")
        self.periodMultiBrand = QtWidgets.QTimeEdit(self.tabPeriod)
        self.periodMultiBrand.setGeometry(QtCore.QRect(190, 0, 61, 22))
        self.periodMultiBrand.setObjectName("periodMultiBrand")
        self.label_3 = QtWidgets.QLabel(self.tabPeriod)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 181, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabPeriod)
        self.label_4.setGeometry(QtCore.QRect(0, 30, 181, 16))
        self.label_4.setObjectName("label_4")
        self.periodMobiBrand = QtWidgets.QTimeEdit(self.tabPeriod)
        self.periodMobiBrand.setGeometry(QtCore.QRect(190, 30, 61, 22))
        self.periodMobiBrand.setObjectName("periodMobiBrand")
        self.timeStars.addTab(self.tabPeriod, "")
        self.monday = QtWidgets.QCheckBox(Form)
        self.monday.setGeometry(QtCore.QRect(0, 90, 91, 17))
        self.monday.setObjectName("monday")
        self.tuesday = QtWidgets.QCheckBox(Form)
        self.tuesday.setGeometry(QtCore.QRect(0, 110, 101, 17))
        self.tuesday.setObjectName("tuesday")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.thursday = QtWidgets.QCheckBox(Form)
        self.thursday.setGeometry(QtCore.QRect(0, 150, 70, 17))
        self.thursday.setObjectName("thursday")
        self.saturday = QtWidgets.QCheckBox(Form)
        self.saturday.setGeometry(QtCore.QRect(0, 190, 70, 17))
        self.saturday.setObjectName("saturday")
        self.sunday = QtWidgets.QCheckBox(Form)
        self.sunday.setGeometry(QtCore.QRect(0, 210, 111, 17))
        self.sunday.setObjectName("sunday")
        self.friday = QtWidgets.QCheckBox(Form)
        self.friday.setGeometry(QtCore.QRect(0, 170, 70, 17))
        self.friday.setObjectName("friday")
        self.wednesday = QtWidgets.QCheckBox(Form)
        self.wednesday.setGeometry(QtCore.QRect(0, 130, 121, 17))
        self.wednesday.setObjectName("wednesday")

        self.retranslateUi(Form)
        self.timeStars.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Время старта мультибренд"))
        self.label_2.setText(_translate("Form", "Время старта Mobi Бренда"))
        self.timeStars.setTabText(self.timeStars.indexOf(self.tabTime), _translate("Form", "Запуск по времени"))
        self.label_3.setText(_translate("Form", "Запускать мультибренд каждые"))
        self.label_4.setText(_translate("Form", "Запускать Mobi бренд каждые"))
        self.timeStars.setTabText(self.timeStars.indexOf(self.tabPeriod), _translate("Form", "Запуск периодически"))
        self.monday.setText(_translate("Form", "Понедельник"))
        self.tuesday.setText(_translate("Form", "Вторник"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.thursday.setText(_translate("Form", "Четверг"))
        self.saturday.setText(_translate("Form", "Суббота"))
        self.sunday.setText(_translate("Form", "Воскресенье"))
        self.friday.setText(_translate("Form", "Пятница"))
        self.wednesday.setText(_translate("Form", "Среда"))
