# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MyProduct\Python\WB\NEW_API\managmentFBS\ui\managerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 500)
        self.updateDbBtn = QtWidgets.QPushButton(Form)
        self.updateDbBtn.setGeometry(QtCore.QRect(10, 10, 170, 25))
        self.updateDbBtn.setObjectName("updateDbBtn")
        self.addFilterStringBtn = QtWidgets.QPushButton(Form)
        self.addFilterStringBtn.setGeometry(QtCore.QRect(190, 10, 170, 25))
        self.addFilterStringBtn.setObjectName("addFilterStringBtn")
        self.filterType = QtWidgets.QComboBox(Form)
        self.filterType.setGeometry(QtCore.QRect(440, 10, 100, 25))
        self.filterType.setObjectName("filterType")
        self.filterType.addItem("")
        self.filterType.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(365, 10, 81, 25))
        self.label.setObjectName("label")
        self.changePrice = QtWidgets.QPushButton(Form)
        self.changePrice.setGeometry(QtCore.QRect(10, 470, 121, 23))
        self.changePrice.setObjectName("changePrice")
        self.changeQuan = QtWidgets.QPushButton(Form)
        self.changeQuan.setGeometry(QtCore.QRect(150, 470, 131, 23))
        self.changeQuan.setObjectName("changeQuan")
        self.changeChar = QtWidgets.QPushButton(Form)
        self.changeChar.setGeometry(QtCore.QRect(300, 470, 151, 23))
        self.changeChar.setObjectName("changeChar")
        self.startExtCharBtn = QtWidgets.QPushButton(Form)
        self.startExtCharBtn.setGeometry(QtCore.QRect(10, 440, 161, 23))
        self.startExtCharBtn.setObjectName("startExtCharBtn")
        self.toFromComboBox = QtWidgets.QComboBox(Form)
        self.toFromComboBox.setGeometry(QtCore.QRect(10, 410, 161, 22))
        self.toFromComboBox.setObjectName("toFromComboBox")
        self.toFromComboBox.addItem("")
        self.toFromComboBox.addItem("")
        self.getLisCardsToFilterBtn = QtWidgets.QPushButton(Form)
        self.getLisCardsToFilterBtn.setGeometry(QtCore.QRect(370, 390, 171, 21))
        self.getLisCardsToFilterBtn.setObjectName("getLisCardsToFilterBtn")
        self.startExtImageBtn = QtWidgets.QPushButton(Form)
        self.startExtImageBtn.setGeometry(QtCore.QRect(190, 440, 171, 23))
        self.startExtImageBtn.setObjectName("startExtImageBtn")
        self.startDeletStoksBtn = QtWidgets.QPushButton(Form)
        self.startDeletStoksBtn.setGeometry(QtCore.QRect(380, 440, 161, 23))
        self.startDeletStoksBtn.setObjectName("startDeletStoksBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.updateDbBtn.setText(_translate("Form", "Обновить базу номенклатур"))
        self.addFilterStringBtn.setText(_translate("Form", "Добавить строку для фильтра"))
        self.filterType.setItemText(0, _translate("Form", "И"))
        self.filterType.setItemText(1, _translate("Form", "ИЛИ"))
        self.label.setText(_translate("Form", "Тип фильтра"))
        self.changePrice.setText(_translate("Form", "Изменить цены"))
        self.changeQuan.setText(_translate("Form", "Изменить наличие"))
        self.changeChar.setText(_translate("Form", "Изменить характеристики"))
        self.startExtCharBtn.setText(_translate("Form", "Стереть свойства"))
        self.toFromComboBox.setItemText(0, _translate("Form", "Из файла"))
        self.toFromComboBox.setItemText(1, _translate("Form", "Из фильтра"))
        self.getLisCardsToFilterBtn.setText(_translate("Form", "Выгрузить товар по фильтру"))
        self.startExtImageBtn.setText(_translate("Form", "Стереть картинки"))
        self.startDeletStoksBtn.setText(_translate("Form", "Выгрузить ШК"))
