# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MyProduct\Python\.git-rewrite\t\WB\managerFBS\ui\managerFBSUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(741, 182)
        self.brandSelector = QtWidgets.QComboBox(Form)
        self.brandSelector.setGeometry(QtCore.QRect(10, 30, 161, 61))
        self.brandSelector.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.brandSelector.setObjectName("brandSelector")
        self.brandSelector.addItem("")
        self.modelSelector = QtWidgets.QComboBox(Form)
        self.modelSelector.setGeometry(QtCore.QRect(190, 30, 161, 61))
        self.modelSelector.setObjectName("modelSelector")
        self.modelSelector.addItem("")
        self.colorSelector = QtWidgets.QComboBox(Form)
        self.colorSelector.setGeometry(QtCore.QRect(370, 30, 161, 61))
        self.colorSelector.setObjectName("colorSelector")
        self.colorSelector.addItem("")
        self.cameraSelector = QtWidgets.QComboBox(Form)
        self.cameraSelector.setGeometry(QtCore.QRect(550, 30, 161, 61))
        self.cameraSelector.setObjectName("cameraSelector")
        self.cameraSelector.addItem("")
        self.printCategorySelector = QtWidgets.QComboBox(Form)
        self.printCategorySelector.setGeometry(QtCore.QRect(370, 100, 161, 22))
        self.printCategorySelector.setObjectName("printCategorySelector")
        self.printCategorySelector.addItem("")
        self.price = QtWidgets.QTextEdit(Form)
        self.price.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.price.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.price.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.price.setObjectName("price")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 91, 16))
        self.label_2.setObjectName("label_2")
        self.discount = QtWidgets.QTextEdit(Form)
        self.discount.setGeometry(QtCore.QRect(110, 150, 81, 21))
        self.discount.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.discount.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.discount.setObjectName("discount")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(420, 10, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(600, 10, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(266, 100, 111, 20))
        self.label_7.setObjectName("label_7")
        self.PushPrice = QtWidgets.QPushButton(Form)
        self.PushPrice.setGeometry(QtCore.QRect(370, 150, 161, 23))
        self.PushPrice.setObjectName("PushPrice")
        self.UpdateData = QtWidgets.QPushButton(Form)
        self.UpdateData.setGeometry(QtCore.QRect(550, 120, 161, 23))
        self.UpdateData.setObjectName("UpdateData")
        self.sellerSelector = QtWidgets.QComboBox(Form)
        self.sellerSelector.setGeometry(QtCore.QRect(10, 100, 161, 22))
        self.sellerSelector.setObjectName("sellerSelector")
        self.sellerSelector.addItem("")
        self.sellerSelector.addItem("")
        self.sellerSelector.addItem("")
        self.PushStocks = QtWidgets.QPushButton(Form)
        self.PushStocks.setGeometry(QtCore.QRect(550, 150, 161, 23))
        self.PushStocks.setObjectName("PushStocks")
        self.availability = QtWidgets.QTextEdit(Form)
        self.availability.setGeometry(QtCore.QRect(210, 150, 81, 21))
        self.availability.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.availability.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.availability.setObjectName("availability")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(230, 130, 47, 13))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.brandSelector.setItemText(0, _translate("Form", "Все"))
        self.modelSelector.setItemText(0, _translate("Form", "Все"))
        self.colorSelector.setItemText(0, _translate("Form", "Все"))
        self.cameraSelector.setItemText(0, _translate("Form", "Все"))
        self.printCategorySelector.setItemText(0, _translate("Form", "Все"))
        self.label.setText(_translate("Form", "Цена продажи"))
        self.label_2.setText(_translate("Form", "Желаемая скидка на сайте"))
        self.discount.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">max</p></body></html>"))
        self.label_3.setText(_translate("Form", "Бренд"))
        self.label_4.setText(_translate("Form", "Модель"))
        self.label_5.setText(_translate("Form", "Цвет"))
        self.label_6.setText(_translate("Form", "Камера"))
        self.label_7.setText(_translate("Form", "Категория принта"))
        self.PushPrice.setText(_translate("Form", "Отправить цены"))
        self.UpdateData.setText(_translate("Form", "Обновить данные"))
        self.sellerSelector.setItemText(0, _translate("Form", "Э.С. Караханян"))
        self.sellerSelector.setItemText(1, _translate("Form", "М.С. Абраамян"))
        self.sellerSelector.setItemText(2, _translate("Form", "С.М. Абраамян"))
        self.PushStocks.setText(_translate("Form", "Отправить наличие"))
        self.availability.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1000</p></body></html>"))
        self.label_8.setText(_translate("Form", "Наличие"))
