# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\MyProduct\Python\WB\FBSStocks\ui\FBSStocks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 259)
        self.selectNomenclatureComboBox = QtWidgets.QComboBox(Form)
        self.selectNomenclatureComboBox.setGeometry(QtCore.QRect(10, 120, 381, 31))
        self.selectNomenclatureComboBox.setObjectName("selectNomenclatureComboBox")
        self.selectNomenclatureComboBox.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 100, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 160, 71, 21))
        self.label_2.setObjectName("label_2")
        self.karahanaynChek = QtWidgets.QCheckBox(Form)
        self.karahanaynChek.setGeometry(QtCore.QRect(90, 190, 81, 17))
        self.karahanaynChek.setAcceptDrops(False)
        self.karahanaynChek.setChecked(True)
        self.karahanaynChek.setObjectName("karahanaynChek")
        self.manvelChek = QtWidgets.QCheckBox(Form)
        self.manvelChek.setGeometry(QtCore.QRect(180, 190, 70, 17))
        self.manvelChek.setChecked(True)
        self.manvelChek.setObjectName("manvelChek")
        self.samvelChek = QtWidgets.QCheckBox(Form)
        self.samvelChek.setGeometry(QtCore.QRect(250, 190, 70, 17))
        self.samvelChek.setChecked(True)
        self.samvelChek.setObjectName("samvelChek")
        self.pushFullStocks = QtWidgets.QPushButton(Form)
        self.pushFullStocks.setGeometry(QtCore.QRect(10, 220, 111, 31))
        self.pushFullStocks.setObjectName("pushFullStocks")
        self.pushEmptyStocks = QtWidgets.QPushButton(Form)
        self.pushEmptyStocks.setGeometry(QtCore.QRect(280, 220, 111, 31))
        self.pushEmptyStocks.setObjectName("pushEmptyStocks")
        self.selectFileButton = QtWidgets.QPushButton(Form)
        self.selectFileButton.setGeometry(QtCore.QRect(10, 39, 381, 31))
        self.selectFileButton.setObjectName("selectFileButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 21, 20))
        self.label_3.setObjectName("label_3")
        self.getNomList = QtWidgets.QPushButton(Form)
        self.getNomList.setGeometry(QtCore.QRect(10, 0, 381, 31))
        self.getNomList.setObjectName("getNomList")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectNomenclatureComboBox.setItemText(0, _translate("Form", "Выберите номенклатуру"))
        self.label.setText(_translate("Form", "Выберите позицию"))
        self.label_2.setText(_translate("Form", "Выберите ИП"))
        self.karahanaynChek.setText(_translate("Form", "Караханян"))
        self.manvelChek.setText(_translate("Form", "Манвел"))
        self.samvelChek.setText(_translate("Form", "Самвел"))
        self.pushFullStocks.setText(_translate("Form", "Выставить наличие"))
        self.pushEmptyStocks.setText(_translate("Form", "Снять наличие"))
        self.selectFileButton.setText(_translate("Form", "Выберите файл с номенклатурой"))
        self.label_3.setText(_translate("Form", "или"))
        self.getNomList.setText(_translate("Form", "Получить список номеклатур"))
