# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MyProduct\Python\archive\parsingAddin\ui\parsing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Parser(object):
    def setupUi(self, Parser):
        Parser.setObjectName("Parser")
        Parser.resize(331, 238)
        self.searchRequestsList = QtWidgets.QTextEdit(Parser)
        self.searchRequestsList.setGeometry(QtCore.QRect(10, 20, 311, 91))
        self.searchRequestsList.setObjectName("searchRequestsList")
        self.label = QtWidgets.QLabel(Parser)
        self.label.setGeometry(QtCore.QRect(10, 0, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Parser)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 151, 21))
        self.label_2.setObjectName("label_2")
        self.countPage = QtWidgets.QTextEdit(Parser)
        self.countPage.setGeometry(QtCore.QRect(170, 120, 51, 21))
        self.countPage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.countPage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.countPage.setObjectName("countPage")
        self.sorting = QtWidgets.QComboBox(Parser)
        self.sorting.setGeometry(QtCore.QRect(170, 150, 121, 21))
        self.sorting.setObjectName("sorting")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.label_3 = QtWidgets.QLabel(Parser)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 141, 21))
        self.label_3.setObjectName("label_3")
        self.allPageCheckBox = QtWidgets.QCheckBox(Parser)
        self.allPageCheckBox.setGeometry(QtCore.QRect(230, 120, 101, 21))
        self.allPageCheckBox.setObjectName("allPageCheckBox")
        self.startButton = QtWidgets.QPushButton(Parser)
        self.startButton.setGeometry(QtCore.QRect(200, 210, 121, 23))
        self.startButton.setObjectName("startButton")
        self.label_4 = QtWidgets.QLabel(Parser)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 241, 21))
        self.label_4.setObjectName("label_4")
        self.timerSave = QtWidgets.QSpinBox(Parser)
        self.timerSave.setGeometry(QtCore.QRect(230, 180, 42, 22))
        self.timerSave.setObjectName("timerSave")
        self.label_5 = QtWidgets.QLabel(Parser)
        self.label_5.setGeometry(QtCore.QRect(280, 180, 21, 21))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Parser)
        QtCore.QMetaObject.connectSlotsByName(Parser)

    def retranslateUi(self, Parser):
        _translate = QtCore.QCoreApplication.translate
        Parser.setWindowTitle(_translate("Parser", "Form"))
        self.label.setText(_translate("Parser", "Введите поисковые запросы через \";\":"))
        self.label_2.setText(_translate("Parser", "Введите количество страниц:"))
        self.sorting.setItemText(0, _translate("Parser", "По популярности"))
        self.sorting.setItemText(1, _translate("Parser", "По рейтингу"))
        self.sorting.setItemText(2, _translate("Parser", "По цене"))
        self.sorting.setItemText(3, _translate("Parser", "По скидке"))
        self.sorting.setItemText(4, _translate("Parser", "По обновлению"))
        self.sorting.setItemText(5, _translate("Parser", "По всем, по порядку"))
        self.label_3.setText(_translate("Parser", "Выберите тип сортировки:"))
        self.allPageCheckBox.setText(_translate("Parser", "Все страницы"))
        self.startButton.setText(_translate("Parser", "Старт"))
        self.label_4.setText(_translate("Parser", "Сохранять промежуточный итог каждые:"))
        self.label_5.setText(_translate("Parser", "мин"))
