# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Rep\Python\archive\PrintHelper\ui\printHelper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 251)
        self.selectFileButt = QtWidgets.QPushButton(Form)
        self.selectFileButt.setGeometry(QtCore.QRect(20, 20, 361, 23))
        self.selectFileButt.setObjectName("selectFileButt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 361, 20))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 361, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.bigButt = QtWidgets.QPushButton(Form)
        self.bigButt.setGeometry(QtCore.QRect(20, 80, 171, 41))
        self.bigButt.setObjectName("bigButt")
        self.bigButt_2 = QtWidgets.QPushButton(Form)
        self.bigButt_2.setGeometry(QtCore.QRect(210, 80, 171, 41))
        self.bigButt_2.setObjectName("bigButt_2")
        self.bigButt_3 = QtWidgets.QPushButton(Form)
        self.bigButt_3.setGeometry(QtCore.QRect(20, 140, 171, 41))
        self.bigButt_3.setObjectName("bigButt_3")
        self.bigButt_4 = QtWidgets.QPushButton(Form)
        self.bigButt_4.setGeometry(QtCore.QRect(210, 140, 171, 41))
        self.bigButt_4.setObjectName("bigButt_4")
        self.bigButt_5 = QtWidgets.QPushButton(Form)
        self.bigButt_5.setGeometry(QtCore.QRect(20, 200, 171, 41))
        self.bigButt_5.setObjectName("bigButt_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectFileButt.setText(_translate("Form", "Выберите файл"))
        self.label.setText(_translate("Form", "Выберите файл с заказом:"))
        self.label_2.setText(_translate("Form", "Выберите режим работы"))
        self.bigButt.setText(_translate("Form", "Большой принтер силикон"))
        self.bigButt_2.setText(_translate("Form", "Средний принтер силикон"))
        self.bigButt_3.setText(_translate("Form", "Маленький принтер силикон"))
        self.bigButt_4.setText(_translate("Form", "Маленький принтер планки"))
        self.bigButt_5.setText(_translate("Form", "Маленький принтер книжки"))
