import transliterate

a = 'прозрачный'

data = '<?xml version = "1.0"?> <!-- Generated by SVGo --> <svg width = "400" height = "300" xmlns = "http://www.w3.org/2000/svg" xmlns:xlink = "http://www.w3.org/1999/xlink" > <text x = "200" y = "150" style = "fill:black;font-size:12;text-anchor:middle" > {} < /text ></svg >'.format(
    transliterate.translit(a, reversed=True))

with open(r'D:\tmp.svg', 'w') as file:
    file.write(data)
    file.close()
