# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\WB\helpTools\Filter\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 67)
        self.selector = QtWidgets.QComboBox(Form)
        self.selector.setGeometry(QtCore.QRect(10, 10, 381, 22))
        self.selector.setObjectName("selector")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(270, 40, 121, 23))
        self.saveButton.setObjectName("saveButton")
        self.ipSelector = QtWidgets.QComboBox(Form)
        self.ipSelector.setGeometry(QtCore.QRect(10, 40, 101, 22))
        self.ipSelector.setObjectName("ipSelector")
        self.ipSelector.addItem("")
        self.ipSelector.addItem("")
        self.ipSelector.addItem("")
        self.ipSelector.addItem("")
        self.vendorCodeChek = QtWidgets.QCheckBox(Form)
        self.vendorCodeChek.setGeometry(QtCore.QRect(160, 40, 70, 21))
        self.vendorCodeChek.setTabletTracking(False)
        self.vendorCodeChek.setChecked(True)
        self.vendorCodeChek.setTristate(False)
        self.vendorCodeChek.setObjectName("vendorCodeChek")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Сохранить эксель"))
        self.ipSelector.setItemText(0, _translate("Form", "Искать по всем"))
        self.ipSelector.setItemText(1, _translate("Form", "Караханян"))
        self.ipSelector.setItemText(2, _translate("Form", "Манвел"))
        self.ipSelector.setItemText(3, _translate("Form", "Самвел"))
        self.vendorCodeChek.setText(_translate("Form", "Артикулы"))
