# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\WB\helpTools\Filter\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 67)
        self.selector = QtWidgets.QComboBox(Form)
        self.selector.setGeometry(QtCore.QRect(10, 10, 381, 22))
        self.selector.setObjectName("selector")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(270, 40, 121, 23))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Сохранить эксель"))
