# Form implementation generated from reading ui file 'e:\MyProduct\Python\WB\createAct\ui\CreateAct.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAct(object):
    def setupUi(self, CreateAct):
        CreateAct.setObjectName("CreateAct")
        CreateAct.resize(388, 370)
        self.centralwidget = QtWidgets.QWidget(parent=CreateAct)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelAcSupp = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAcSupp.setObjectName("labelAcSupp")
        self.gridLayout.addWidget(self.labelAcSupp, 2, 0, 1, 1)
        self.lineEditScan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScan.setObjectName("lineEditScan")
        self.gridLayout.addWidget(self.lineEditScan, 1, 0, 1, 1)
        self.labelScan = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScan.setObjectName("labelScan")
        self.gridLayout.addWidget(self.labelScan, 0, 0, 1, 1)
        self.tableWidgetSupp = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetSupp.setObjectName("tableWidgetSupp")
        self.tableWidgetSupp.setColumnCount(0)
        self.tableWidgetSupp.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetSupp, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButtonCreateActs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCreateActs.setObjectName("pushButtonCreateActs")
        self.gridLayout_2.addWidget(self.pushButtonCreateActs, 1, 0, 1, 1)
        CreateAct.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CreateAct)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 22))
        self.menubar.setObjectName("menubar")
        CreateAct.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CreateAct)
        self.statusbar.setObjectName("statusbar")
        CreateAct.setStatusBar(self.statusbar)

        self.retranslateUi(CreateAct)
        QtCore.QMetaObject.connectSlotsByName(CreateAct)

    def retranslateUi(self, CreateAct):
        _translate = QtCore.QCoreApplication.translate
        CreateAct.setWindowTitle(_translate("CreateAct", "MainWindow"))
        self.labelAcSupp.setText(_translate("CreateAct", "Активные поставки"))
        self.labelScan.setText(_translate("CreateAct", "Отсканируйте поставку или введите номер вручную"))
        self.pushButtonCreateActs.setText(_translate("CreateAct", "Создать акты"))
