# Form implementation generated from reading ui file 'D:\Python\WB\changePrice\changePrice.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChangePrice(object):
    def setupUi(self, ChangePrice):
        ChangePrice.setObjectName("ChangePrice")
        ChangePrice.resize(605, 451)
        self.centralwidget = QtWidgets.QWidget(parent=ChangePrice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSearchLine = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelSearchLine.setObjectName("labelSearchLine")
        self.gridLayout.addWidget(self.labelSearchLine, 4, 1, 1, 1)
        self.pushButtonPushPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPushPrice.setObjectName("pushButtonPushPrice")
        self.gridLayout.addWidget(self.pushButtonPushPrice, 8, 2, 1, 1)
        self.pushButtoGetCurPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtoGetCurPrice.setObjectName("pushButtoGetCurPrice")
        self.gridLayout.addWidget(self.pushButtoGetCurPrice, 7, 1, 1, 1)
        self.labelChooseExcel = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelChooseExcel.setObjectName("labelChooseExcel")
        self.gridLayout.addWidget(self.labelChooseExcel, 0, 1, 1, 1)
        self.labelTableListNom = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTableListNom.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTableListNom.setObjectName("labelTableListNom")
        self.gridLayout.addWidget(self.labelTableListNom, 2, 1, 1, 2)
        self.tableWidgetListNom = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetListNom.setObjectName("tableWidgetListNom")
        self.tableWidgetListNom.setColumnCount(0)
        self.tableWidgetListNom.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetListNom, 6, 1, 1, 2)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 8, 1, 1, 1)
        self.pushButtonChoisExcel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonChoisExcel.setObjectName("pushButtonChoisExcel")
        self.gridLayout.addWidget(self.pushButtonChoisExcel, 0, 2, 1, 1)
        self.lineEditSearchInTable = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSearchInTable.setObjectName("lineEditSearchInTable")
        self.gridLayout.addWidget(self.lineEditSearchInTable, 4, 2, 1, 1)
        self.pushButtonSortTable = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSortTable.setObjectName("pushButtonSortTable")
        self.gridLayout.addWidget(self.pushButtonSortTable, 5, 2, 1, 1)
        ChangePrice.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ChangePrice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        ChangePrice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ChangePrice)
        self.statusbar.setObjectName("statusbar")
        ChangePrice.setStatusBar(self.statusbar)
        self.updateDB = QtGui.QAction(parent=ChangePrice)
        self.updateDB.setObjectName("updateDB")
        self.updateTokens = QtGui.QAction(parent=ChangePrice)
        self.updateTokens.setObjectName("updateTokens")
        self.menu.addAction(self.updateDB)
        self.menu.addSeparator()
        self.menu.addAction(self.updateTokens)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ChangePrice)
        QtCore.QMetaObject.connectSlotsByName(ChangePrice)

    def retranslateUi(self, ChangePrice):
        _translate = QtCore.QCoreApplication.translate
        ChangePrice.setWindowTitle(_translate("ChangePrice", "MainWindow"))
        self.labelSearchLine.setText(_translate("ChangePrice", "Найти номенклатуру"))
        self.pushButtonPushPrice.setText(_translate("ChangePrice", "Отправить новые цены и скидки"))
        self.pushButtoGetCurPrice.setText(_translate("ChangePrice", "Получить текущие цены"))
        self.labelChooseExcel.setText(_translate("ChangePrice", "Выберите Excel файл из 1С"))
        self.labelTableListNom.setText(_translate("ChangePrice", "Список номенклатур в файле"))
        self.pushButtonCancel.setText(_translate("ChangePrice", "Отменить изменения"))
        self.pushButtonChoisExcel.setText(_translate("ChangePrice", "Выбрать файл"))
        self.pushButtonSortTable.setText(_translate("ChangePrice", "Отсортировать список"))
        self.menu.setTitle(_translate("ChangePrice", "Меню"))
        self.updateDB.setText(_translate("ChangePrice", "Обновить базу данных"))
        self.updateTokens.setText(_translate("ChangePrice", "Обновить токены"))
